# Generated by Django 5.0.4 on 2024-06-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0003_remove_user_is_active_remove_user_is_admin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="啟用"),
        ),
    ]
