# Generated by Django 5.0.4 on 2024-06-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0004_user_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_admin",
            field=models.BooleanField(default=False, verbose_name="管理員"),
        ),
    ]
