# Generated by Django 5.0.4 on 2024-06-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0006_remove_user_is_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
    ]
