# Generated by Django 5.0.4 on 2024-07-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0014_game_chatroom_message_role_item_server_role_server_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["timestamp"]},
        ),
        migrations.AddField(
            model_name="chatroom",
            name="topic",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="聊天主題"
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="swappost",
            name="swap_time",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_email_verified",
            field=models.BooleanField(default=False, verbose_name="信箱驗證"),
        ),
        migrations.AlterUniqueTogether(
            name="server",
            unique_together={("game", "name")},
        ),
    ]
