# Generated by Django 5.0.4 on 2024-07-10 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0016_alter_swappost_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="swappost",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="swappost",
            name="desired_item",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="swappost",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="swap_posts",
                to="mysite.item",
            ),
        ),
        migrations.AlterField(
            model_name="swappost",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "等待交換"),
                    ("in_progress", "交換進行中"),
                    ("completed", "交換已完成"),
                    ("canceled", "交換已取消"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="swappost",
            name="swap_location",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="swappost",
            name="swap_role_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="swappost",
            name="swap_time",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="swappost",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="swappost",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
