# Generated by Django 5.0.4 on 2024-07-12 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0017_alter_swappost_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="game",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="mysite.game"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="server",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="mysite.server",
            ),
        ),
    ]
