# Generated by Django 5.0.4 on 2024-07-12 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0018_item_game_item_server"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mysite.game"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="server",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mysite.server"
            ),
        ),
    ]
