# Generated by Django 5.0.4 on 2024-07-13 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0019_alter_item_game_alter_item_server"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="chat_room",
        ),
        migrations.RemoveField(
            model_name="item",
            name="game",
        ),
        migrations.RemoveField(
            model_name="item",
            name="role",
        ),
        migrations.RemoveField(
            model_name="item",
            name="server",
        ),
        migrations.RemoveField(
            model_name="swappost",
            name="item",
        ),
        migrations.RemoveField(
            model_name="message",
            name="sender",
        ),
        migrations.RemoveField(
            model_name="role",
            name="server",
        ),
        migrations.RemoveField(
            model_name="role",
            name="user",
        ),
        migrations.RenameField(
            model_name="swappost",
            old_name="swap_role_name",
            new_name="role_name",
        ),
        migrations.AddField(
            model_name="swappost",
            name="game",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="mysite.game"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="swappost",
            name="item_description",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="swappost",
            name="item_image",
            field=models.ImageField(blank=True, null=True, upload_to="items/"),
        ),
        migrations.AddField(
            model_name="swappost",
            name="item_name",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="swappost",
            name="server",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="mysite.server",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="swappost",
            name="desired_item",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="swappost",
            name="status",
            field=models.CharField(
                choices=[
                    ("WAITING", "等待交換"),
                    ("IN_PROGRESS", "交換進行中"),
                    ("COMPLETED", "交換已完成"),
                    ("CANCELLED", "交換已取消"),
                ],
                default="WAITING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="swappost",
            name="swap_location",
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name="ChatRoom",
        ),
        migrations.DeleteModel(
            name="Item",
        ),
        migrations.DeleteModel(
            name="Message",
        ),
        migrations.DeleteModel(
            name="Role",
        ),
    ]
