# Generated by Django 5.0.4 on 2024-07-23 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0021_swapmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="swappost",
            name="swapper",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="swap_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
