# Generated by Django 5.0.4 on 2024-07-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0023_alter_swappost_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="swappost",
            name="is_owner_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="swappost",
            name="is_swapper_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
