# Generated by Django 5.0.4 on 2024-07-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0024_swappost_is_owner_confirmed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="swappost",
            name="confirmation_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="swappost",
            name="status",
            field=models.CharField(
                choices=[
                    ("WAITING", "待交換"),
                    ("IN_PROGRESS", "進行中"),
                    ("PENDING_COMPLETION", "等待確認完成"),
                    ("PENDING_CANCELLATION", "等待確認取消"),
                    ("COMPLETED", "已完成"),
                    ("CANCELLED", "已取消"),
                ],
                default="WAITING",
                max_length=20,
            ),
        ),
    ]
