# Generated by Django 5.0.4 on 2024-07-25 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0025_swappost_confirmation_deadline_alter_swappost_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="swappost",
            name="cancellation_initiator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cancellation_initiated_swaps",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
